# Generated by Django 4.2 on 2025-01-17 12:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_shop', '0002_alter_menuitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='table_number',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(message='First name should only contain letters.', regex='^[a-zA-Z]+$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(message='First lastname should only contain letters.', regex='^[a-zA-Z]+$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(help_text='رمز عبور باید حداقل ۸ کاراکتر و ترکیبی از حروف، اعداد و کاراکترهای خاص باشد.', max_length=100, validators=[django.core.validators.MinLengthValidator(8, message='رمز عبور باید حداقل ۸ کاراکتر باشد.'), django.core.validators.RegexValidator(message='رمز عبور باید حداقل شامل یک حرف کوچک، یک حرف بزرگ، یک عدد و یک کاراکتر خاص باشد.', regex='^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(help_text='فقط ۹ رقم شماره تلفن را وارد کنید (بدون +98).', max_length=10, validators=[django.core.validators.RegexValidator(message='شماره تلفن باید ۹ رقم باشد.', regex='^\\d{9}$')]),
        ),
    ]
