# Generated by Django 4.2 on 2025-01-17 13:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_shop', '0003_alter_table_table_number_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(help_text='رمز عبور باید حداقل ۸ کاراکتر و ترکیبی از حروف، اعداد و کاراکترهای خاص باشد.', max_length=100, validators=[django.core.validators.MinLengthValidator(8, message='رمز عبور باید حداقل ۸ کاراکتر باشد.'), django.core.validators.RegexValidator(message='رمز عبور باید حداقل شامل یک حرف کوچک، یک حرف بزرگ، یک عدد و یک کاراکتر خاص باشد.', regex='/^(?=.*\\d)(?=.*[A-Z])(?=.*[a-z])(?=.*[^\\w\\d\\s:])([^\\s]){8,16}$/gm')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(help_text='فقط ۹ رقم شماره تلفن را وارد کنید (بدون +98).', max_length=11, validators=[django.core.validators.RegexValidator(message='شماره تلفن باید ۹ رقم باشد.', regex='^\\d{9}$')]),
        ),
    ]
