# Generated by Django 4.2 on 2025-01-17 13:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_shop', '0007_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(help_text='فقط 10 رقم شماره تلفن را وارد کنید (بدون +98).', max_length=11, validators=[django.core.validators.RegexValidator(message='شماره تلفن باید 10 رقم باشد.', regex='^\\d{9}$')]),
        ),
    ]
