# Generated by Django 4.2 on 2025-01-19 02:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_shop', '0009_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(help_text='فقط 10 رقم آخر شماره تلفن را وارد کنید.', max_length=11, validators=[django.core.validators.RegexValidator(regex='^\\d{9}$')]),
        ),
    ]
